# Generated by Django 4.2.16 on 2026-08-20 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('document_upload', 'Document uploaded'), ('chat_query', 'Chat query'), ('summary_generated', 'Summary generated'), ('pdf_export', 'PDF export'), ('user_login', 'User login'), ('document_failed', 'Document processing failed'), ('feedback_given', 'Feedback given')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='evt_user_created_idx'), models.Index(fields=['event_type', '-created_at'], name='evt_type_created_idx')],
            },
        ),
    ]
