DOC_TYPE_PDF  = 'pdf'
DOC_TYPE_DOCX = 'docx'
DOC_TYPE_TXT  = 'txt'
DOCUMENT_TYPES = [DOC_TYPE_PDF, DOC_TYPE_DOCX, DOC_TYPE_TXT]

STATUS_PENDING    = 'pending'
STATUS_PROCESSING = 'processing'
STATUS_COMPLETED  = 'completed'
STATUS_FAILED     = 'failed'
DOCUMENT_STATUSES = [STATUS_PENDING, STATUS_PROCESSING, STATUS_COMPLETED, STATUS_FAILED]

SESSION_ACTIVE   = 'active'
SESSION_ARCHIVED = 'archived'
SESSION_STATUSES = [SESSION_ACTIVE, SESSION_ARCHIVED]

ROLE_USER      = 'user'
ROLE_ASSISTANT = 'assistant'
MESSAGE_ROLES  = [ROLE_USER, ROLE_ASSISTANT]

EVENT_UPLOAD  = 'document_upload'
EVENT_QUERY   = 'chat_query'
EVENT_SUMMARY = 'summary_generated'
EVENT_EXPORT  = 'pdf_export'
EVENT_LOGIN   = 'user_login'
EVENT_FEEDBACK = 'feedback_given'
ANALYTICS_EVENTS = [EVENT_UPLOAD, EVENT_QUERY, EVENT_SUMMARY, EVENT_EXPORT,
                    EVENT_LOGIN, EVENT_FEEDBACK]
