# Generated by Django 4.2.16 on 2026-08-20 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_verified', models.BooleanField(default=False)),
                ('document_quota', models.IntegerField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user profile',
            },
        ),
    ]
