import LegalLayout from '../components/landing/LegalLayout'

/**
 * Public terms of use. Companion to the Privacy Policy — both are linked from
 * the registration consent checkbox and the legal page footer.
 */
export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Use"
      updated="June 27, 2026"
      intro="By creating an account and using RAG Chatbot, you agree to these Terms of Use. RAG Chatbot is an academic / portfolio project that demonstrates Retrieval-Augmented Generation and is provided for educational and evaluation purposes."
      sections={[
        {
          heading: '1. Use of the service',
          list: [
            'You must provide accurate account information and keep your credentials secure.',
            'You are responsible for the documents you upload and the questions you ask.',
            'Do not use the app for unlawful purposes or to upload content you do not have the right to use.',
          ],
        },
        {
          heading: '2. Your content',
          body: [
            'You retain ownership of the documents you upload. By uploading them, you grant the app permission to process them — splitting, embedding, and retrieving passages — solely to provide answers to you.',
            'As this is a demonstration project, please do not upload confidential, sensitive, or regulated material.',
          ],
        },
        {
          heading: '3. AI-generated answers',
          body: [
            'Answers are generated by a language model based on your documents and may be incomplete or incorrect. Do not rely on them as professional, legal, medical, or financial advice.',
            'Always verify important information against the cited sources.',
          ],
        },
        {
          heading: '4. Availability & “as is”',
          body: [
            'The service is provided “as is,” without warranties of any kind, and may be unavailable, reset, or changed at any time without notice.',
            'To the fullest extent permitted by law, we are not liable for any damages arising from your use of the app.',
          ],
        },
        {
          heading: '5. Account termination',
          body: ['We may suspend or remove accounts that misuse the service. You may stop using the app and request deletion of your account at any time.'],
        },
        {
          heading: '6. Changes to these terms',
          body: ['We may update these terms as the project evolves. Continued use after changes constitutes acceptance of the updated terms.'],
        },
      ]}
    />
  )
}
