# Generated by Django 4.2.16 on 2026-08-20 10:41

from django.conf import settings
import django.contrib.postgres.search
import django.core.validators
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The extensions have to exist before a vector(384) column can be
        # created, and docker/postgres/init.sql only runs once, against the
        # database initdb creates. Anything else — the test database
        # pytest-django builds, a CI service container, a managed instance
        # created from a snapshot — never sees it, and the first migration
        # fails with 'type "vector" does not exist'.
        #
        # Declaring them here makes the requirement part of the schema history
        # instead of a container detail. Django's CreateExtension is already a
        # no-op on any non-PostgreSQL connection, so the SQLite path is
        # unaffected, and CREATE EXTENSION IF NOT EXISTS is idempotent where
        # init.sql already ran.
        VectorExtension(),
        TrigramExtension(),
        UnaccentExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_mongo_id', models.CharField(blank=True, db_index=True, help_text='The MongoDB ObjectId this row was migrated from, if any.', max_length=24, null=True, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_type', models.CharField(max_length=16)),
                ('file_size', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration_ms', models.IntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('vector_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('page_number', models.IntegerField(default=1)),
                ('start_char', models.IntegerField(default=0)),
                ('end_char', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('content_tsv', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcollection'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='documentcollection',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_collection_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['owner'], name='chunk_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='chunk_doc_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_chunk_index_per_document'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-created_at'], name='doc_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'status'], name='doc_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'created_at'], name='doc_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('owner', 'file_hash'), name='uniq_document_hash_per_owner'),
        ),
    ]
